---
spring:
  config:
    activate:
      on-profile: local

jwt:
  secret: local-secret
  # 2시간 = 2 * 60 * 60 * 1000
  access-token-expire-time: 1209600000

  refresh-secret: local-refresh-secret
  # 2주 = 14 * 24 * 60 * 60 * 1000
  refresh-token-expire-time: 1209600000

---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  secret: dev-secret
  # 2시간 = 2 * 60 * 60 * 1000
  access-token-expire-time: 1209600000

  refresh-secret: dev-refresh-secret
  # 2주 = 14 * 24 * 60 * 60 * 1000
  refresh-token-expire-time: 1209600000

---
spring:
  config:
    activate:
      on-profile: prod

jwt:
  secret: and0LWV4YW1wbGUtYWNjZXNzLXRva2VuLXNlY3JldC1rZXk=
  # 2시간 = 2 * 60 * 60 * 1000
  access-token-expire-time: 1209600000

  refresh-secret: and0LWV4YW1wbGUtcmVmcmVzaC10b2tlbi1zZWNyZXQta2V5
  # 2주 = 14 * 24 * 60 * 60 * 1000
  refresh-token-expire-time: 1209600000
