version: '3.8'

services:
  cache:
    container_name: carrot-cache
    platform: linux/amd64
    image: redis:7.0.11
    ports:
      - "6379:6379"
    volumes:
      - ./redis/volume:/data

  database:
    container_name: carrot-database
    platform: linux/amd64
    image: mysql:8.0.33
    ports:
      - "3306:3306"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=carrot
      - MYSQL_USER=carrot
      - MYSQL_PASSWORD=carrot
      - TZ=Asia/Seoul
    volumes:
      - ./mysql/volume:/var/lib/mysql