spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carrot
    username: carrot
    password: carrot

  data:
    redis:
      host: localhost
      port: 6379

  sql:
    init:
      mode: always
      data-locations: classpath:sql/init-seed.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

jwt:
  access-secret: and0LWV4YW1wbGUtYWNjZXNzLXRva2VuLXNlY3JldC1rZXk=
  # 2시간 = 2 * 60 * 60 * 1000
  access-token-expire-time: 1209600000

  refresh-secret: and0LWV4YW1wbGUtcmVmcmVzaC10b2tlbi1zZWNyZXQta2V5
  # 2주 = 14 * 24 * 60 * 60 * 1000
  refresh-token-expire-time: 1209600000