spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danggeun
    username: danggeun
    password: danggeun

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
